### ISSUE TITLE
Automatic publishing to package managers

### ISSUE THREAD

**Issue by EncodedVenom** [Ukendio/jecs#153]
## Describe your Feature
This issue is about the addition of CI scripts that would automate publishing to supported platforms on release (wally, npm, pesde, etc). While we already have a wally CI script for this, we do not have such a script for npm or pesde.

## Implementation

This would be implemented using the release CI script.

## Alternatives

Publishing manually. This is relatively infeasible at scale for fairly obvious reasons.

## Considerations

Successful implementation of this issue would resolve the problem of having to manually publish to all providers for the package.

## Tasks

The following tasks need to be done for this issue to be complete:

@Ukendio specific:

- [x] Expose an NPM_AUTH_TOKEN secret for the runner to use [in accordance with this](https://github.com/marketplace/actions/publish-to-npm)

Non-specific:

- [ ] (Pesde) add manifest info
- [ ] (Pesde) implement CI script
- [x] (npm) implement CI script

**Comment by Mark-Marks** [comment]
Steps to get the pesde token on Windows:
1. Install pesde
2. `pesde auth login`
Then due to Windows not allowing users to get tokens from the credential manager, you need to create a rust app to get the token.
3. `cargo create get-pesde-token`
4. `cd get-pesde-token`
5. `cargo add keyring -F windows-native`
6.
```rs
use keyring::{Entry, Result};
 
fn main() -> Result<()> {
    let entry = Entry::new("tokens", "pesde")?;
    let password = entry.get_password()?;
    println!("Password: {}", password);
    Ok(())
}
```
7. `cargo run`
Make sure to copy the entire token *including* `Bearer`.

**Comment by EncodedVenom** [comment]
With pesde support being cancelled and the npm support now live, this is now a successfully closed issue.
