### ISSUE TITLE
Better documentation needed

### ISSUE THREAD

**Issue by Ukendio** [Ukendio/jecs#50]
We need to add comprehensive documentation to our GitHub repository to help new contributors understand the project, its structure, and how to contribute. Proper documentation will also assist users in understanding how to use the project effectively.

**Documentation should include:**

1. **Overview**
   - Brief description of the project.
   - Key features and functionalities.

2. **Installation**
   - Prerequisites.
   - Step-by-step installation guide.
   - Configuration instructions.

3. **Usage**
   - How to run the project.
   - Basic usage examples.
   - Explanation of main components.
   
4. **Contributing**
   - Contribution guidelines.
   - How to report issues.
   - How to submit pull requests.
   - Code of conduct.

5. **FAQs**
   - Common issues and troubleshooting.
   - Frequently asked questions.

6. **License**
   - Licensing information.

**Additional Notes:**

- Use Markdown for documentation.
- Include images/screenshots where applicable.
- Ensure the documentation is easy to navigate and well-organized.

**Tasks:**

- [x] Create an overview section.
- [x] Write installation instructions.
- [x] Provide usage examples.
- [x] Draft contributing guidelines.
- [ ] Compile FAQs.
- [x] Add license information.

**Comment by sasial-dev** [comment]
It should also include a "Migrating from matter page" to highlight the differences between it and matter.

**Comment by Ukendio** [comment]
@addbounty $50

**Comment by addbounty** [comment]
[![banner](https://bountybot.dev/api/display/github/Ukendio/jecs/50/banner?v=e72fe47a-61cd-4696-9fc8-12acffa24134)](https://bountybot.dev/github/Ukendio/jecs/issues/50)
[![button](https://bountybot.dev/api/display/github/Ukendio/jecs/50/button?v=e72fe47a-61cd-4696-9fc8-12acffa24134)](https://bountybot.dev/github/Ukendio/jecs/issues/50)

Make a Draft PR **early** so others can see you are working on it! To automatically create one:

```sh
# Using npx (installed if you have NodeJS/npm)
npx bountybot start Ukendio/jecs#50

# Or, use cargo (installed if you have Rust)
cargo install bounty
bounty start Ukendio/jecs#50
```

When merged, you will receive the bounty!

**Comment by L9VRS** [comment]
@addbounty $50.00

**Comment by EncodedVenom** [comment]
Those who are coming by and seeing this for the first time, the addbounty bot apparently no longer works.
